// astro-docs/src/components/examples/19-save-load-layout.vue
<template>
  <div class="demo-controls">
    <button
      class="demo-btn"
      @click="save">Save</button>
    <button
      class="demo-btn demo-btn--ghost"
      @click="load">Load</button>
    <span
      v-if="status"
      class="demo-status">{{ status }}</span>
  </div>

  <GridLayout
    v-model:layout="layout"
    :col-num="12"
    :row-height="60"
    show-grid-lines>
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';

  const STORAGE_KEY = 'keystonegrid-example-19-layout';

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 3, x: 0, y: 0 },
    { h: 2, i: '1', w: 3, x: 3, y: 0 },
  ]);

  const status = ref('');

  function save(): void {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(layout.value));
    status.value = 'Saved.';
  }

  function load(): void {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      status.value = 'Nothing saved yet.';
      return;
    }
    layout.value = JSON.parse(raw) as TLayout;
    status.value = 'Loaded.';
  }
</script>

<style scoped>
.demo-controls {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.demo-btn {
  background: var(--kg-blueprint);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.demo-btn--ghost {
  background: transparent;
  border: 1px solid var(--kg-line-light);
  color: var(--kg-text-hi-light);
}

.demo-status {
  color: var(--kg-text-lo-light);
  font-size: 12px;
  font-style: italic;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>

// astro-docs/src/components/examples-react/19-save-load-layout.tsx
import { useState } from 'react';
import { GridLayout, GridItem, useLayoutStorage } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './19-save-load-layout.css';

const STORAGE_KEY = 'keystone-dashboard-layout-example-19-layout';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 2, i: '1', w: 3, x: 3, y: 0 },
];

export default function SaveLoadLayout() {
  const [layout, setLayout] = useState<TLayout>(initialLayout);
  const [status, setStatus] = useState('');
  const { load, save } = useLayoutStorage(STORAGE_KEY);

  function handleSave(): void {
    save(layout);
    setStatus('Saved.');
  }

  function handleLoad(): void {
    const loaded = load();
    if (!loaded) {
      setStatus('Nothing saved yet.');
      return;
    }
    setLayout(loaded);
    setStatus('Loaded.');
  }

  return (
    <>
      <div className="demo-controls">
        <button className="demo-btn" onClick={handleSave} type="button">Save</button>
        <button className="demo-btn demo-btn--ghost" onClick={handleLoad} type="button">Load</button>
        {status ? <span className="demo-status">{status}</span> : null}
      </div>

      <GridLayout colNum={12} layout={layout} onLayoutChange={setLayout} rowHeight={60} showGridLines>
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>
    </>
  );
}
