// astro-docs/src/components/examples/31-per-item-auto-height.vue
<template>
  <div class="demo-controls">
    <button
      class="demo-btn"
      @click="addLine">+ Add a line</button>
    <button
      class="demo-btn demo-btn--ghost"
      @click="removeLine">- Remove a line</button>
  </div>

  <GridLayout
    v-model:layout="layout"
    :col-num="12"
    :row-height="30"
    show-grid-lines>
    <GridItem
      v-for="item in layout"
      :key="item.i"
      auto-height
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        <p
          v-for="(line, index) in lines"
          :key="index">{{ line }}</p>
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 4, x: 0, y: 0 },
  ]);

  const lines = ref(['One line of content.']);

  function addLine(): void {
    lines.value = [...lines.value, `Line ${lines.value.length + 1} of content.`];
  }

  function removeLine(): void {
    if (lines.value.length > 1) {
      lines.value = lines.value.slice(0, -1);
    }
  }
</script>

<style scoped>
.demo-controls {
  margin-bottom: 16px;
}

.demo-btn {
  background: var(--kg-blueprint);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.demo-btn--ghost {
  background: transparent;
  border: 1px solid var(--kg-line-light);
  color: var(--kg-text-hi-light);
}

.example-item {
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 10px 12px;
  width: 100%;
}

.example-item p {
  margin: 0 0 4px;
}
</style>

// astro-docs/src/components/examples-react/31-per-item-auto-height.tsx
﻿import { useState } from 'react';
import { GridLayout, GridItem } from 'keystone-dashboard-layout-react';
import 'keystone-dashboard-layout-react/style.css';
import type { TLayout } from 'keystone-dashboard-layout-core';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import './31-per-item-auto-height.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 4, x: 0, y: 0, autoHeight: true },
];

export default function PerItemAutoHeight() {
  const [layout, setLayout] = useState<TLayout>(initialLayout);
  const [lines, setLines] = useState(['One line of content.']);

  function addLine(): void {
    setLines((current) => [...current, `Line ${current.length + 1} of content.`]);
  }

  function removeLine(): void {
    setLines((current) => (current.length > 1 ? current.slice(0, -1) : current));
  }

  return (
    <>
      <div className="demo-controls">
        <button className="demo-btn" onClick={addLine} type="button">+ Add a line</button>
        <button className="demo-btn demo-btn--ghost" onClick={removeLine} type="button">- Remove a line</button>
      </div>

      <GridLayout colNum={12} layout={layout} onLayoutChange={setLayout} rowHeight={30} showGridLines>
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">
              {lines.map((line, index) => <p key={index}>{line}</p>)}
            </div>
          </GridItem>
        ))}
      </GridLayout>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}
