// astro-docs/src/components/examples/34-outside-drop-accept-payload.vue
<template>
  <div class="demo-controls">
    <div
      class="outside-source outside-source--accepted"
      draggable="true"
      @dragstart="onDragStart(true, $event)">
      widget (accepted)
    </div>
    <div
      class="outside-source outside-source--rejected"
      draggable="true"
      @dragstart="onDragStart(false, $event)">
      not-a-widget (rejected)
    </div>
  </div>

  <div class="drop-zone-frame">
    <GridLayout
      v-model:layout="layout"
      allow-outside-drop
      :col-num="12"
      height-mode="fit"
      :outside-drop-accept="outsideDropAccept"
      :row-height="60"
      show-grid-lines
      @item-dropped-from-outside="onDropped">
      <GridItem
        v-for="item in layout"
        :key="item.i"
        :h="item.h"
        :i="item.i"
        :w="item.w"
        :x="item.x"
        :y="item.y">
        <div class="example-item">
          {{ item.i }}
        </div>
      </GridItem>
    </GridLayout>
  </div>

  <p class="demo-description">Last payload: {{ lastPayload ?? 'none yet' }}</p>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, readOutsideDropPayload, type TLayout } from 'keystone-dashboard-layout-vue';
  import 'keystone-dashboard-layout-vue/style.css';

  interface IWidgetPayload {
    kind: string;
    label: string;
  }

  const layout = ref<TLayout>([]);
  const lastPayload = ref<string | null>(null);
  let nextId = 0;

  function onDragStart(isWidget: boolean, event?: DragEvent): void {
    const payload: IWidgetPayload = isWidget
      ? { kind: 'widget', label: 'A real widget' }
      : { kind: 'not-a-widget', label: 'Should be rejected' };
    event?.dataTransfer?.setData('application/json', JSON.stringify(payload));
    // A second, marker-only MIME type carrying no value of its own —
    // `dataTransfer.types` (unlike `.getData()`) is readable during
    // dragenter/dragover, so this is what `outsideDropAccept` below
    // actually checks. Only the real widget sets it.
    if (isWidget) {
      event?.dataTransfer?.setData('application/x-widget', '');
    }
  }

  function outsideDropAccept(dataTransfer: DataTransfer | null): boolean {
    // Deliberately checks `.types`, not the payload itself — reading
    // `.getData()`'s actual value only works at `drop` time; during
    // dragenter/dragover (when this is called) it always returns an
    // empty string, so a payload-parsing check here would silently
    // reject every drag, real widget or not.
    return !!dataTransfer?.types.includes('application/x-widget');
  }

  function onDropped({ x, y, w, h, dataTransfer }: { x: number; y: number; w: number; h: number; dataTransfer: DataTransfer }): void {
    const payload = readOutsideDropPayload<IWidgetPayload>(dataTransfer, 'application/json');
    lastPayload.value = JSON.stringify(payload);
    layout.value.push({ h, i: String(nextId), w, x, y });
    nextId += 1;
  }
</script>

<style scoped>
.demo-controls {
  margin-bottom: 16px;
}

.drop-zone-frame {
  border: 1px dashed var(--kg-line-light);
  height: 200px;
}

.outside-source {
  border-radius: 6px;
  cursor: grab;
  display: inline-block;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.outside-source--accepted {
  background: var(--kg-amber);
  color: #2b1b02;
}

.outside-source--rejected {
  background: var(--kg-paper-3);
  border: 1px dashed var(--kg-line-light);
  color: var(--kg-text-lo-light);
  margin-left: 8px;
}

.demo-description {
  color: var(--kg-text-lo-light);
  font-size: 12.5px;
  font-family: var(--kg-font-mono);
  margin-top: 12px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>

// astro-docs/src/components/examples-react/34-outside-drop-accept-payload.tsx
import { useRef, useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import { readOutsideDropPayload } from '@keystone-dashboard-layout/core';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './34-outside-drop-accept-payload.css';

interface IWidgetPayload {
  kind: string;
  label: string;
}

export default function OutsideDropAcceptPayload() {
  const [layout, setLayout] = useState<TLayout>([]);
  const [lastPayload, setLastPayload] = useState<string | null>(null);
  const nextId = useRef(0);

  function handleDragStart(isWidget: boolean, event: React.DragEvent<HTMLDivElement>): void {
    const payload: IWidgetPayload = isWidget
      ? { kind: 'widget', label: 'A real widget' }
      : { kind: 'not-a-widget', label: 'Should be rejected' };
    event.dataTransfer.setData('application/json', JSON.stringify(payload));
    // A second, marker-only MIME type carrying no value of its own —
    // `dataTransfer.types` (unlike `.getData()`) is readable during
    // dragenter/dragover, so this is what `outsideDropAccept` below
    // actually checks. Only the real widget sets it.
    if (isWidget) {
      event.dataTransfer.setData('application/x-widget', '');
    }
  }

  function outsideDropAccept(dataTransfer: DataTransfer | null): boolean {
    // Deliberately checks `.types`, not the payload itself — reading
    // `.getData()`'s actual value only works at `drop` time; during
    // dragenter/dragover (when this is called) it always returns an
    // empty string, so a payload-parsing check here would silently
    // reject every drag, real widget or not.
    return !!dataTransfer?.types.includes('application/x-widget');
  }

  function handleOutsideDrop({ x, y, w, h, dataTransfer }: { x: number; y: number; w: number; h: number; dataTransfer: DataTransfer | null }): void {
    const payload = readOutsideDropPayload<IWidgetPayload>(dataTransfer, 'application/json');
    setLastPayload(JSON.stringify(payload));
    setLayout((current) => [...current, { h, i: String(nextId.current), w, x, y }]);
    nextId.current += 1;
  }

  return (
    <>
      <div className="demo-controls">
        <div className="outside-source outside-source--accepted" draggable="true" onDragStart={(e) => handleDragStart(true, e)}>
          widget (accepted)
        </div>
        <div className="outside-source outside-source--rejected" draggable="true" onDragStart={(e) => handleDragStart(false, e)}>
          not-a-widget (rejected)
        </div>
      </div>

      <div className="drop-zone-frame">
        <GridLayout
          allowOutsideDrop
          colNum={12}
          heightMode="fit"
          layout={layout}
          onLayoutChange={setLayout}
          onOutsideDrop={handleOutsideDrop}
          outsideDropAccept={outsideDropAccept}
          rowHeight={60}
          showGridLines
        >
          {layout.map((item) => (
            <GridItem i={item.i} key={item.i}>
              <div className="example-item">{item.i}</div>
            </GridItem>
          ))}
        </GridLayout>
      </div>

      <p className="demo-description">Last payload: {lastPayload ?? 'none yet'}</p>
    </>
  );
}
