// angular-examples-app/src/app/examples/40-layout-lifecycle-events.component.ts
﻿import { Component } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from 'keystone-dashboard-layout-angular';
import type { TLayout } from 'keystone-dashboard-layout-core';
import { LayoutJsonViewerComponent } from '../harness/layout-json-viewer.component';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 2, i: '1', w: 3, x: 3, y: 0 },
];

@Component({
  selector: 'app-layout-lifecycle-events-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, LayoutJsonViewerComponent],
  template: `
    <kdl-grid-layout
      [colNum]="12"
      [layout]="layout"
      (columnsChanged)="logEvent('columnsChanged')"
      (dragStart)="logEvent('dragStart: ' + $event)"
      (dragMove)="logEvent('dragMove: ' + $event)"
      (dragEnd)="logEvent('dragEnd: ' + $event)"
      (layoutChange)="handleLayoutChange($event)"
      (layoutReady)="logEvent('layoutReady')"
      [rowHeight]="60"
      [showGridLines]="true"
    >
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="example-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>

    <div class="event-log-panel">
      <p class="event-log__label">LIFECYCLE LOG</p>
      <ul class="event-log">
        @for (entry of events; track $index) {
          <li class="event-log__entry">{{ entry }}</li>
        }
      </ul>
    </div>

    <layout-json-viewer [layout]="layout" />
  `,
})
export class LayoutLifecycleEventsDemoComponent {
  layout: TLayout = initialLayout;
  events: string[] = [];

  logEvent(name: string): void {
    this.events = [name, ...this.events].slice(0, 20);
  }

  handleLayoutChange(next: TLayout): void {
    this.logEvent('layoutChange');
    this.layout = next;
  }
}

// astro-docs/src/components/examples-react/40-layout-lifecycle-events.tsx
﻿import { useState } from 'react';
import { GridLayout, GridItem } from 'keystone-dashboard-layout-react';
import 'keystone-dashboard-layout-react/style.css';
import type { TLayout } from 'keystone-dashboard-layout-core';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import '../examples-react/shared-example-item.css';
import './40-layout-lifecycle-events.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 2, i: '1', w: 3, x: 3, y: 0 },
];

export default function LayoutLifecycleEvents() {
  const [layout, setLayout] = useState<TLayout>(initialLayout);
  const [events, setEvents] = useState<string[]>([]);

  function logEvent(name: string): void {
    setEvents((current) => [name, ...current].slice(0, 20));
  }

  function handleLayoutChange(next: TLayout): void {
    logEvent('onLayoutChange');
    setLayout(next);
  }

  return (
    <>
      <GridLayout
        colNum={12}
        layout={layout}
        onColumnsChanged={() => logEvent('onColumnsChanged')}
        onDragEnd={(id) => logEvent(`onDragEnd: ${id}`)}
        onDragMove={(id) => logEvent(`onDragMove: ${id}`)}
        onDragStart={(id) => logEvent(`onDragStart: ${id}`)}
        onLayoutChange={handleLayoutChange}
        onLayoutReady={() => logEvent('onLayoutReady')}
        rowHeight={60}
        showGridLines
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>

      <div className="event-log-panel">
        <p className="event-log__label">LIFECYCLE LOG</p>
        <ul className="event-log">
          {events.map((entry, index) => <li className="event-log__entry" key={index}>{entry}</li>)}
        </ul>
      </div>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}
