// astro-docs/src/components/examples/44-grid-dimensions.vue
<template>
  <div class="demo-controls">
    <ExampleNumberField
      v-model="rowHeight"
      label="rowHeight"
      :max="200"
      :min="20" />
    <ExampleNumberField
      v-model="colNum"
      label="colNum"
      :max="24"
      :min="2" />
    <ExampleNumberField
      v-model="marginX"
      label="margin[0]"
      :max="40"
      :min="0" />
    <ExampleNumberField
      v-model="marginY"
      label="margin[1]"
      :max="40"
      :min="0" />
    <ExampleToggle
      v-model="showGridLines"
      label="showGridLines" />
  </div>

  <GridLayout
    v-model:layout="layout"
    :col-num="colNum"
    :margin="[marginX, marginY]"
    :row-height="rowHeight"
    :show-grid-lines="showGridLines">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from 'keystone-dashboard-layout-vue';
  import 'keystone-dashboard-layout-vue/style.css';
  import ExampleNumberField from '../harness/ExampleNumberField.vue';
  import ExampleToggle from '../harness/ExampleToggle.vue';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const showGridLines = ref(true);

  const rowHeight = ref(60);
  const colNum = ref(12);
  const marginX = ref(10);
  const marginY = ref(10);

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 3, x: 0, y: 0 },
    { h: 2, i: '1', w: 3, x: 3, y: 0 },
    { h: 2, i: '2', w: 3, x: 6, y: 0 },
  ]);
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>

// astro-docs/src/components/examples-react/44-grid-dimensions.tsx
import { useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import ExampleNumberField from '../harness-react/ExampleNumberField';
import ExampleToggle from '../harness-react/ExampleToggle';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import '../examples-react/shared-example-item.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 2, i: '1', w: 3, x: 3, y: 0 },
  { h: 2, i: '2', w: 3, x: 6, y: 0 },
];

export default function GridDimensions() {
  const [rowHeight, setRowHeight] = useState(60);
  const [colNum, setColNum] = useState(12);
  const [marginX, setMarginX] = useState(10);
  const [marginY, setMarginY] = useState(10);
  const [showGridLines, setShowGridLines] = useState(true);
  const [layout, setLayout] = useState<TLayout>(initialLayout);

  return (
    <>
      <div className="demo-controls">
        <ExampleNumberField label="rowHeight" max={200} min={20} onChange={setRowHeight} value={rowHeight} />
        <ExampleNumberField label="colNum" max={24} min={2} onChange={setColNum} value={colNum} />
        <ExampleNumberField label="margin[0]" max={40} min={0} onChange={setMarginX} value={marginX} />
        <ExampleNumberField label="margin[1]" max={40} min={0} onChange={setMarginY} value={marginY} />
        <ExampleToggle checked={showGridLines} label="showGridLines" onChange={setShowGridLines} />
      </div>

      <GridLayout colNum={colNum} layout={layout} margin={[marginX, marginY]} onLayoutChange={setLayout} rowHeight={rowHeight} showGridLines={showGridLines}>
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}
