// angular-examples-app/src/app/examples/46-align-distribute-selected.component.ts
import { Component, ViewChild } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import { ECompactType } from '@keystone-dashboard-layout/core';
import type { TLayout } from '@keystone-dashboard-layout/core';

const initialLayout: TLayout = [
  { h: 2, i: 'a', w: 2, x: 0, y: 0 },
  { h: 2, i: 'b', w: 3, x: 3, y: 2 },
  { h: 2, i: 'c', w: 2, x: 7, y: 1 },
  { h: 2, i: 'd', w: 2, x: 5, y: 4 },
];

@Component({
  selector: 'app-align-distribute-selected-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent],
  template: `
    <div class="demo-controls">
      <span class="demo-description">Selected: {{ selectedItems.length ? selectedItems.join(', ') : 'none' }}</span>
      <button class="demo-btn" type="button" (click)="grid.alignSelected('left')">Align left</button>
      <button class="demo-btn" type="button" (click)="grid.alignSelected('center-x')">Align center-x</button>
      <button class="demo-btn" type="button" (click)="grid.alignSelected('right')">Align right</button>
      <button class="demo-btn" type="button" (click)="grid.alignSelected('top')">Align top</button>
      <button class="demo-btn demo-btn--ghost" type="button" (click)="grid.distributeSelected('horizontal')">Distribute horizontal</button>
      <button class="demo-btn demo-btn--ghost" type="button" (click)="grid.distributeSelected('vertical')">Distribute vertical</button>
    </div>

    <kdl-grid-layout #grid [compactType]="ECompactType.NONE" [layout]="layout" [multiSelect]="true" (layoutChange)="layout = $event" (selectionChanged)="selectedItems = $event" [rowHeight]="60" [showGridLines]="true">
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="example-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>
  `,
})
export class AlignDistributeSelectedDemoComponent {
  @ViewChild('grid') grid!: GridLayoutComponent;
  readonly ECompactType = ECompactType;
  layout: TLayout = initialLayout;
  selectedItems: (string | number)[] = [];
}

// astro-docs/src/components/examples-react/46-align-distribute-selected.tsx
﻿import { useRef, useState } from 'react';
import { GridLayout, GridItem, type IGridLayoutHandle } from 'keystone-dashboard-layout-react';
import 'keystone-dashboard-layout-react/style.css';
import { ECompactType } from 'keystone-dashboard-layout-core';
import type { TLayout } from 'keystone-dashboard-layout-core';
import '../examples-react/shared-example-item.css';
import './46-align-distribute-selected.css';

const initialLayout: TLayout = [
  { h: 2, i: 'a', w: 2, x: 0, y: 0 },
  { h: 2, i: 'b', w: 3, x: 3, y: 2 },
  { h: 2, i: 'c', w: 2, x: 7, y: 1 },
  { h: 2, i: 'd', w: 2, x: 5, y: 4 },
];

export default function AlignDistributeSelected() {
  const [layout, setLayout] = useState<TLayout>(initialLayout);
  const [selectedItems, setSelectedItems] = useState<(string | number)[]>([]);
  const gridRef = useRef<IGridLayoutHandle>(null);

  return (
    <>
      <div className="demo-controls">
        <span className="demo-description">Selected: {selectedItems.join(', ') || 'none'}</span>
        <button className="demo-btn" onClick={() => gridRef.current?.alignSelected('left')} type="button">Align left</button>
        <button className="demo-btn" onClick={() => gridRef.current?.alignSelected('center-x')} type="button">Align center-x</button>
        <button className="demo-btn" onClick={() => gridRef.current?.alignSelected('right')} type="button">Align right</button>
        <button className="demo-btn" onClick={() => gridRef.current?.alignSelected('top')} type="button">Align top</button>
        <button className="demo-btn demo-btn--ghost" onClick={() => gridRef.current?.distributeSelected('horizontal')} type="button">
          Distribute horizontal
        </button>
        <button className="demo-btn demo-btn--ghost" onClick={() => gridRef.current?.distributeSelected('vertical')} type="button">
          Distribute vertical
        </button>
      </div>

      <GridLayout
        compactType={ECompactType.NONE}
        layout={layout}
        multiSelect
        onLayoutChange={setLayout}
        onSelectionChanged={setSelectedItems}
        ref={gridRef}
        rowHeight={60}
        showGridLines
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>
    </>
  );
}
