// packages/angular/e2e-fixture/app.component.ts
import { Component } from '@angular/core';
import { BasicGridComponent } from './scenarios/basic-grid.component';
import { DynamicItemsComponent } from './scenarios/dynamic-items.component';
import { DragResizeComponent } from './scenarios/drag-resize.component';
import { KeyboardAccessibilityComponent } from './scenarios/keyboard-accessibility.component';
import { AdvancedFeaturesComponent } from './scenarios/advanced-features.component';
import { MultiSelectComponent } from './scenarios/multi-select.component';
import { ResponsiveComponent } from './scenarios/responsive.component';
import { RtlComponent } from './scenarios/rtl.component';
import { CrossGridComponent } from './scenarios/cross-grid.component';
import { ExternalDropComponent } from './scenarios/external-drop.component';
import { ItemOverridesComponent } from './scenarios/item-overrides.component';

type TScenarioId = `basic` | `dynamic` | `drag-resize` | `keyboard` | `advanced-features` | `multi-select` | `responsive` | `rtl` | `cross-grid` | `external-drop` | `item-overrides`;

/**
 * Minimal scenario switcher for the e2e test fixture — deliberately
 * not a showcase/demo app (no descriptive copy, no styling beyond
 * what's needed for items to have a visible bounding box). Just
 * enough routing between scenarios for Playwright to reach each one
 * via a `data-testid` nav button, mirroring the mechanism (not the
 * presentation) of React's own `e2e-fixture/App.tsx`. Full parity with
 * React's own 11-scenario e2e suite as of this writing.
 */
@Component({
  imports: [
    BasicGridComponent,
    DynamicItemsComponent,
    DragResizeComponent,
    KeyboardAccessibilityComponent,
    AdvancedFeaturesComponent,
    MultiSelectComponent,
    ResponsiveComponent,
    RtlComponent,
    CrossGridComponent,
    ExternalDropComponent,
    ItemOverridesComponent,
  ],
  selector: `app-root`,
  standalone: true,
  template: `
    <nav class="fixture-nav">
      @for (scenario of scenarios; track scenario.id) {
        <button [attr.data-testid]="'nav-' + scenario.id" type="button" (click)="activeId = scenario.id">{{ scenario.id }}</button>
      }
    </nav>
    <main class="fixture-main">
      @switch (activeId) {
        @case ('basic') { <app-basic-grid /> }
        @case ('dynamic') { <app-dynamic-items /> }
        @case ('drag-resize') { <app-drag-resize /> }
        @case ('keyboard') { <app-keyboard-accessibility /> }
        @case ('advanced-features') { <app-advanced-features /> }
        @case ('multi-select') { <app-multi-select /> }
        @case ('responsive') { <app-responsive /> }
        @case ('rtl') { <app-rtl /> }
        @case ('cross-grid') { <app-cross-grid /> }
        @case ('external-drop') { <app-external-drop /> }
        @case ('item-overrides') { <app-item-overrides /> }
      }
    </main>
  `,
})
export class AppComponent {
  readonly scenarios: { id: TScenarioId }[] = [
    { id: `basic` },
    { id: `dynamic` },
    { id: `drag-resize` },
    { id: `keyboard` },
    { id: `advanced-features` },
    { id: `multi-select` },
    { id: `responsive` },
    { id: `rtl` },
    { id: `cross-grid` },
    { id: `external-drop` },
    { id: `item-overrides` },
  ];
  activeId: TScenarioId = `basic`;
}

// packages/react/e2e-fixture/App.tsx
import { useState } from 'react';
import BasicGrid from './scenarios/BasicGrid';
import DragResize from './scenarios/DragResize';
import DynamicItems from './scenarios/DynamicItems';
import Responsive from './scenarios/Responsive';
import KeyboardAccessibility from './scenarios/KeyboardAccessibility';
import MultiSelect from './scenarios/MultiSelect';
import CrossGrid from './scenarios/CrossGrid';
import Rtl from './scenarios/Rtl';
import ItemOverrides from './scenarios/ItemOverrides';
import ExternalDrop from './scenarios/ExternalDrop';
import AdvancedFeatures from './scenarios/AdvancedFeatures';

const scenarios = [
  { id: `basic`, component: BasicGrid },
  { id: `drag-resize`, component: DragResize },
  { id: `dynamic`, component: DynamicItems },
  { id: `responsive`, component: Responsive },
  { id: `keyboard`, component: KeyboardAccessibility },
  { id: `multi-select`, component: MultiSelect },
  { id: `cross-grid`, component: CrossGrid },
  { id: `rtl`, component: Rtl },
  { id: `item-overrides`, component: ItemOverrides },
  { id: `external-drop`, component: ExternalDrop },
  { id: `advanced-features`, component: AdvancedFeatures },
] as const;

/**
 * Minimal scenario switcher for the e2e test fixture — deliberately
 * not a showcase/demo app (no descriptive copy, no styling beyond
 * what's needed for items to have a visible bounding box). Just
 * enough routing between scenarios for Playwright to reach each one
 * via a `data-testid` nav button, mirroring the mechanism (not the
 * presentation) of the Vue package's own demo app nav.
 */
export default function App(): React.JSX.Element {
  const [activeId, setActiveId] = useState<(typeof scenarios)[number]['id']>(`basic`);
  const Active = scenarios.find(scenario => scenario.id === activeId)!.component;

  return (
    <div>
      <nav className="fixture-nav">
        {scenarios.map(scenario => (
          <button
            data-testid={`nav-${scenario.id}`}
            key={scenario.id}
            onClick={() => setActiveId(scenario.id)}
            type="button"
          >
            {scenario.id}
          </button>
        ))}
      </nav>
      <main className="fixture-main">
        <Active />
      </main>
    </div>
  );
}
