// astro-docs/src/components/examples-react/04-multiple-grids.tsx
import { useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './04-multiple-grids.css';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';

export default function MultipleGrids() {
  const [layoutA, setLayoutA] = useState<TLayout>([
    { h: 2, i: 'a0', w: 3, x: 0, y: 0 },
    { h: 2, i: 'a1', w: 3, x: 3, y: 0 },
  ]);
  const [layoutB, setLayoutB] = useState<TLayout>([
    { h: 2, i: 'b0', w: 3, x: 0, y: 0 },
    { h: 2, i: 'b1', w: 3, x: 3, y: 0 },
  ]);

  return (
    <>
      <div className="grids-row">
        <div className="grid-column">
          <p className="grid-label">Grid A</p>
          <GridLayout colNum={6} layout={layoutA} onLayoutChange={setLayoutA} rowHeight={60} showGridLines>
            {layoutA.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
        <div className="grid-column">
          <p className="grid-label">Grid B</p>
          <GridLayout colNum={6} layout={layoutB} onLayoutChange={setLayoutB} rowHeight={60} showGridLines>
            {layoutB.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
      </div>

      <LayoutJsonViewer label="Grid A" layout={layoutA} />
      <LayoutJsonViewer label="Grid B" layout={layoutB} />
    </>
  );
}

// astro-docs/src/components/examples/04-multiple-grids.vue
<template>
  <div class="grids-row">
    <div class="grid-column">
      <p class="grid-label">Grid A</p>
      <GridLayout
        v-model:layout="layoutA"
        :col-num="6"
        :row-height="60"
        show-grid-lines>
        <GridItem
          v-for="item in layoutA"
          :key="item.i"
          :h="item.h"
          :i="item.i"
          :w="item.w"
          :x="item.x"
          :y="item.y">
          <div class="example-item">
            {{ item.i }}
          </div>
        </GridItem>
      </GridLayout>
    </div>
    <div class="grid-column">
      <p class="grid-label">Grid B</p>
      <GridLayout
        v-model:layout="layoutB"
        :col-num="6"
        :row-height="60"
        show-grid-lines>
        <GridItem
          v-for="item in layoutB"
          :key="item.i"
          :h="item.h"
          :i="item.i"
          :w="item.w"
          :x="item.x"
          :y="item.y">
          <div class="example-item">
            {{ item.i }}
          </div>
        </GridItem>
      </GridLayout>
    </div>
  </div>

  <LayoutJsonViewer label="Grid A" :layout="layoutA" />
  <LayoutJsonViewer label="Grid B" :layout="layoutB" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const layoutA = ref<TLayout>([
    { h: 2, i: 'a0', w: 3, x: 0, y: 0 },
    { h: 2, i: 'a1', w: 3, x: 3, y: 0 },
  ]);

  const layoutB = ref<TLayout>([
    { h: 2, i: 'b0', w: 3, x: 0, y: 0 },
    { h: 2, i: 'b1', w: 3, x: 3, y: 0 },
  ]);
</script>

<style scoped>
.grids-row {
  display: grid;
  gap: 16px;
  grid-template-columns: 1fr 1fr;
}

.grid-label {
  color: var(--kg-text-lo-light);
  font-family: var(--kg-font-mono);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.05em;
  margin: 0 0 8px;
  text-transform: uppercase;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
