// astro-docs/src/components/examples-react/11-outside-drag-drop.tsx
import { useRef, useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './11-outside-drag-drop.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
];

export default function OutsideDragDrop() {
  const [layout, setLayout] = useState<TLayout>(initialLayout);
  const nextId = useRef(1);

  function handleDragStart(event: React.DragEvent<HTMLDivElement>): void {
    event.dataTransfer.setData('text/plain', 'from-outside');
  }

  function handleOutsideDrop({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    setLayout((current) => [...current, { h, i: String(nextId.current), w, x, y }]);
    nextId.current += 1;
  }

  return (
    <>
      <div className="demo-controls">
        <div className="outside-source" draggable="true" onDragStart={handleDragStart}>
          drag me in
        </div>
      </div>

      <GridLayout
        allowOutsideDrop
        colNum={12}
        layout={layout}
        onLayoutChange={setLayout}
        onOutsideDrop={handleOutsideDrop}
        outsideDropHeight={2}
        outsideDropWidth={3}
        rowHeight={60}
        showGridLines
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>
    </>
  );
}

// astro-docs/src/components/examples/11-outside-drag-drop.vue
<template>
  <div class="demo-controls">
    <div
      class="outside-source"
      draggable="true"
      @dragstart="onDragStart">
      drag me in
    </div>
  </div>

  <GridLayout
    v-model:layout="layout"
    allow-outside-drop
    :col-num="12"
    :outside-drop-height="2"
    :outside-drop-width="3"
    :row-height="60"
    show-grid-lines
    @item-dropped-from-outside="onDropped">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 3, x: 0, y: 0 },
  ]);

  let nextId = 1;

  function onDragStart(event: DragEvent): void {
    event.dataTransfer?.setData('text/plain', 'from-outside');
  }

  function onDropped({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    layout.value.push({ h, i: String(nextId), w, x, y });
    nextId += 1;
  }
</script>

<style scoped>
.demo-controls {
  margin-bottom: 16px;
}

.outside-source {
  background: var(--kg-amber);
  border-radius: 6px;
  color: #2b1b02;
  cursor: grab;
  display: inline-block;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
