// angular-examples-app/src/app/examples/14-border-radius.component.ts
﻿import { Component } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from 'keystone-dashboard-layout-angular';
import type { TLayout } from 'keystone-dashboard-layout-core';
import { ExampleToggleComponent } from '../harness/example-toggle.component';
import { ExampleNumberFieldComponent } from '../harness/example-number-field.component';
import { LayoutJsonViewerComponent } from '../harness/layout-json-viewer.component';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 2, x: 0, y: 0 },
  { h: 2, i: '1', w: 2, x: 2, y: 0 },
  { h: 2, i: '2', w: 2, x: 4, y: 0 },
];

@Component({
  selector: 'app-border-radius-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, ExampleToggleComponent, ExampleNumberFieldComponent, LayoutJsonViewerComponent],
  template: `
    <div class="demo-controls">
      <example-toggle [checked]="useBorderRadius" (checkedChange)="useBorderRadius = $event" label="useBorderRadius"></example-toggle>
      <example-number-field [value]="borderRadiusPx" (valueChange)="borderRadiusPx = $event" label="borderRadiusPx" [min]="0" [max]="40"></example-number-field>
    </div>

    <kdl-grid-layout
      [borderRadiusPx]="borderRadiusPx"
      [colNum]="12"
      [layout]="layout"
      (layoutChange)="layout = $event"
      [rowHeight]="60"
      [showGridLines]="true"
      [useBorderRadius]="useBorderRadius"
    >
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="border-radius-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>

    <layout-json-viewer [layout]="layout" />
  `,
  styles: [`
    .border-radius-item {
      align-items: center;
      background: var(--kg-panel);
      border: 1px solid var(--kg-line-light);
      border-radius: inherit;
      color: var(--kg-text-hi-light);
      display: flex;
      font-family: var(--kg-font-mono);
      height: 100%;
      justify-content: center;
      width: 100%;
    }
  `],
})
export class BorderRadiusDemoComponent {
  useBorderRadius = true;
  borderRadiusPx = 16;
  layout: TLayout = initialLayout;
}

// astro-docs/src/components/examples/14-border-radius.vue
<template>
  <div class="demo-controls">
    <ExampleToggle
      v-model="useBorderRadius"
      label="useBorderRadius" />
    <ExampleNumberField
      v-model="borderRadiusPx"
      label="borderRadiusPx"
      :max="40"
      :min="0" />
  </div>

  <GridLayout
    v-model:layout="layout"
    :border-radius-px="borderRadiusPx"
    :col-num="12"
    :row-height="60"
    show-grid-lines
    :use-border-radius="useBorderRadius">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';
  import ExampleToggle from '../harness/ExampleToggle.vue';
  import ExampleNumberField from '../harness/ExampleNumberField.vue';

  const useBorderRadius = ref(true);
  const borderRadiusPx = ref(16);

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 2, x: 0, y: 0 },
    { h: 2, i: '1', w: 2, x: 2, y: 0 },
    { h: 2, i: '2', w: 2, x: 4, y: 0 },
  ]);
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: inherit;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
