// astro-docs/src/components/examples-react/14-border-radius.tsx
import { useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import ExampleToggle from '../harness-react/ExampleToggle';
import ExampleNumberField from '../harness-react/ExampleNumberField';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import '../examples-react/shared-example-item.css';
import './14-border-radius.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 2, x: 0, y: 0 },
  { h: 2, i: '1', w: 2, x: 2, y: 0 },
  { h: 2, i: '2', w: 2, x: 4, y: 0 },
];

export default function BorderRadius() {
  const [useBorderRadius, setUseBorderRadius] = useState(true);
  const [borderRadiusPx, setBorderRadiusPx] = useState(16);
  const [layout, setLayout] = useState<TLayout>(initialLayout);

  return (
    <>
      <div className="demo-controls">
        <ExampleToggle checked={useBorderRadius} label="useBorderRadius" onChange={setUseBorderRadius} />
        <ExampleNumberField label="borderRadiusPx" max={40} min={0} onChange={setBorderRadiusPx} value={borderRadiusPx} />
      </div>

      <GridLayout
        borderRadiusPx={borderRadiusPx}
        colNum={12}
        layout={layout}
        onLayoutChange={setLayout}
        rowHeight={60}
        showGridLines
        useBorderRadius={useBorderRadius}
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}

// astro-docs/src/components/examples/14-border-radius.vue
<template>
  <div class="demo-controls">
    <ExampleToggle
      v-model="useBorderRadius"
      label="useBorderRadius" />
    <ExampleNumberField
      v-model="borderRadiusPx"
      label="borderRadiusPx"
      :max="40"
      :min="0" />
  </div>

  <GridLayout
    v-model:layout="layout"
    :border-radius-px="borderRadiusPx"
    :col-num="12"
    :row-height="60"
    show-grid-lines
    :use-border-radius="useBorderRadius">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';
  import ExampleToggle from '../harness/ExampleToggle.vue';
  import ExampleNumberField from '../harness/ExampleNumberField.vue';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const useBorderRadius = ref(true);
  const borderRadiusPx = ref(16);

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 2, x: 0, y: 0 },
    { h: 2, i: '1', w: 2, x: 2, y: 0 },
    { h: 2, i: '2', w: 2, x: 4, y: 0 },
  ]);
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: inherit;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
