// astro-docs/src/components/examples-react/23-outside-drag-drop-multiple-grids.tsx
import { useRef, useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './04-multiple-grids.css';
import './11-outside-drag-drop.css';

export default function OutsideDragDropMultipleGrids() {
  const [layoutA, setLayoutA] = useState<TLayout>([]);
  const [layoutB, setLayoutB] = useState<TLayout>([]);
  const nextId = useRef(0);

  function handleDragStart(event: React.DragEvent<HTMLDivElement>): void {
    event.dataTransfer.setData('text/plain', 'from-outside');
  }

  function handleDroppedA({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    setLayoutA((current) => [...current, { h, i: `a${nextId.current}`, w, x, y }]);
    nextId.current += 1;
  }

  function handleDroppedB({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    setLayoutB((current) => [...current, { h, i: `b${nextId.current}`, w, x, y }]);
    nextId.current += 1;
  }

  return (
    <>
      <div className="demo-controls">
        <div className="outside-source" draggable="true" onDragStart={handleDragStart}>
          drag me in
        </div>
      </div>

      <div className="grids-row">
        <div className="grid-column">
          <p className="grid-label">Grid A</p>
          <GridLayout allowOutsideDrop colNum={6} layout={layoutA} onLayoutChange={setLayoutA} onOutsideDrop={handleDroppedA} rowHeight={60} showGridLines>
            {layoutA.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
        <div className="grid-column">
          <p className="grid-label">Grid B</p>
          <GridLayout allowOutsideDrop colNum={6} layout={layoutB} onLayoutChange={setLayoutB} onOutsideDrop={handleDroppedB} rowHeight={60} showGridLines>
            {layoutB.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
      </div>
    </>
  );
}

// astro-docs/src/components/examples/23-outside-drag-drop-multiple-grids.vue
<template>
  <div class="demo-controls">
    <div
      class="outside-source"
      draggable="true"
      @dragstart="onDragStart">
      drag me in
    </div>
  </div>

  <div class="grids-row">
    <div class="grid-column">
      <p class="grid-label">Grid A</p>
      <GridLayout
        v-model:layout="layoutA"
        allow-outside-drop
        :col-num="6"
        :row-height="60"
        show-grid-lines
        @item-dropped-from-outside="onDroppedA">
        <GridItem
          v-for="item in layoutA"
          :key="item.i"
          :h="item.h"
          :i="item.i"
          :w="item.w"
          :x="item.x"
          :y="item.y">
          <div class="example-item">{{ item.i }}</div>
        </GridItem>
      </GridLayout>
    </div>
    <div class="grid-column">
      <p class="grid-label">Grid B</p>
      <GridLayout
        v-model:layout="layoutB"
        allow-outside-drop
        :col-num="6"
        :row-height="60"
        show-grid-lines
        @item-dropped-from-outside="onDroppedB">
        <GridItem
          v-for="item in layoutB"
          :key="item.i"
          :h="item.h"
          :i="item.i"
          :w="item.w"
          :x="item.x"
          :y="item.y">
          <div class="example-item">{{ item.i }}</div>
        </GridItem>
      </GridLayout>
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';

  const layoutA = ref<TLayout>([]);
  const layoutB = ref<TLayout>([]);

  let nextId = 0;

  function onDragStart(event: DragEvent): void {
    event.dataTransfer?.setData('text/plain', 'from-outside');
  }

  function onDroppedA({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    layoutA.value.push({ h, i: `a${nextId}`, w, x, y });
    nextId += 1;
  }

  function onDroppedB({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    layoutB.value.push({ h, i: `b${nextId}`, w, x, y });
    nextId += 1;
  }
</script>

<style scoped>
.demo-controls {
  margin-bottom: 16px;
}

.outside-source {
  background: var(--kg-amber);
  border-radius: 6px;
  color: #2b1b02;
  cursor: grab;
  display: inline-block;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.grids-row {
  display: grid;
  gap: 16px;
  grid-template-columns: 1fr 1fr;
}

.grid-label {
  color: var(--kg-text-lo-light);
  font-family: var(--kg-font-mono);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.05em;
  margin: 0 0 8px;
  text-transform: uppercase;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
