// astro-docs/src/components/examples-react/32-snap-to-grid.tsx
import { useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import { ECompactType } from '@keystone-dashboard-layout/core';
import type { TLayout } from '@keystone-dashboard-layout/core';
import ExampleToggle from '../harness-react/ExampleToggle';
import ExampleNumberField from '../harness-react/ExampleNumberField';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import '../examples-react/shared-example-item.css';

// compactType: NONE — without this, automatic vertical compaction
// would fight against the snapped position itself, potentially
// undoing/shifting the item right after snapToGrid places it.
const initialLayout: TLayout = [
  { h: 2, i: '0', w: 2, x: 0, y: 6 },
  { h: 2, i: '1', w: 8, x: 0, y: 0 },
];

export default function SnapToGrid() {
  const [snapToGrid, setSnapToGrid] = useState(true);
  const [snapThreshold, setSnapThreshold] = useState(2);
  const [showGridLines, setShowGridLines] = useState(true);
  const [layout, setLayout] = useState<TLayout>(initialLayout);

  return (
    <>
      <div className="demo-controls">
        <ExampleToggle checked={snapToGrid} label="snapToGrid" onChange={setSnapToGrid} />
        <ExampleToggle checked={showGridLines} label="showGridLines" onChange={setShowGridLines} />
        <ExampleNumberField label="snapThreshold" max={4} min={0} onChange={setSnapThreshold} value={snapThreshold} />
      </div>

      <GridLayout
        colNum={12}
        compactType={ECompactType.NONE}
        layout={layout}
        onLayoutChange={setLayout}
        rowHeight={60}
        showGridLines={showGridLines}
        snapThreshold={snapThreshold}
        snapToGrid={snapToGrid}
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}

// astro-docs/src/components/examples/32-snap-to-grid.vue
<template>
  <div class="demo-controls">
    <ExampleToggle
      v-model="snapToGrid"
      label="snapToGrid" />
    <ExampleToggle
      v-model="showGridLines"
      label="showGridLines" />
    <ExampleNumberField
      v-model="snapThreshold"
      label="snapThreshold"
      :max="4"
      :min="0" />
  </div>

  <GridLayout
    v-model:layout="layout"
    :col-num="12"
    :compact-type="ECompactType.NONE"
    :row-height="60"
    :show-grid-lines="showGridLines"
    :snap-threshold="snapThreshold"
    :snap-to-grid="snapToGrid">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, ECompactType, type TLayout } from 'keystone-dashboard-layout-vue';
  import 'keystone-dashboard-layout-vue/style.css';
  import ExampleToggle from '../harness/ExampleToggle.vue';
  import ExampleNumberField from '../harness/ExampleNumberField.vue';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const snapToGrid = ref(true);
  const snapThreshold = ref(2);
  const showGridLines = ref(true);

  // compactType: NONE — without this, automatic vertical compaction
  // would fight against the snapped position itself, potentially
  // undoing/shifting the item right after snapToGrid places it.
  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 2, x: 0, y: 6 },
    { h: 2, i: '1', w: 8, x: 0, y: 0 },
  ]);
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
