// angular-examples-app/src/app/examples/34-outside-drop-accept-payload.component.ts
﻿import { Component } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from 'keystone-dashboard-layout-angular';
import { readOutsideDropPayload } from 'keystone-dashboard-layout-core';
import type { TLayout } from 'keystone-dashboard-layout-core';

interface IWidgetPayload {
  kind: string;
  label: string;
}

@Component({
  selector: 'app-outside-drop-accept-payload-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent],
  template: `
    <div class="demo-controls">
      <div class="outside-source outside-source--accepted" draggable="true" (dragstart)="handleDragStart(true, $event)">
        widget (accepted)
      </div>
      <div class="outside-source outside-source--rejected" draggable="true" (dragstart)="handleDragStart(false, $event)">
        not-a-widget (rejected)
      </div>
    </div>

    <div class="drop-zone-frame">
      <kdl-grid-layout
        [allowOutsideDrop]="true"
        [colNum]="12"
        heightMode="fit"
        [layout]="layout"
        (layoutChange)="layout = $event"
        (itemDroppedFromOutside)="handleOutsideDrop($event)"
        [outsideDropAccept]="outsideDropAccept"
        [rowHeight]="60"
        [showGridLines]="true"
      >
        @for (item of layout; track item.i) {
          <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
            <div class="example-item">{{ item.i }}</div>
          </kdl-grid-item>
        }
      </kdl-grid-layout>
    </div>

    <p class="demo-description">Last payload: {{ lastPayload ?? 'none yet' }}</p>
  `,
  styles: [`
    .outside-source {
      border-radius: 6px;
      cursor: grab;
      display: inline-block;
      font-family: var(--kg-font-mono);
      font-size: 12px;
      padding: 6px 12px;
    }
    .drop-zone-frame {
      border: 1px dashed var(--kg-line-light);
      height: 200px;
    }
    .outside-source--accepted {
      background: var(--kg-amber);
      color: #2b1b02;
    }
    .outside-source--rejected {
      background: var(--kg-paper-3);
      border: 1px dashed var(--kg-line-light);
      color: var(--kg-text-lo-light);
      margin-left: 8px;
    }
    .demo-description {
      color: var(--kg-text-lo-light);
      font-size: 12.5px;
      font-family: var(--kg-font-mono);
      margin-top: 12px;
    }
  `],
})
export class OutsideDropAcceptPayloadDemoComponent {
  layout: TLayout = [];
  lastPayload: string | null = null;
  private nextId = 0;

  handleDragStart(isWidget: boolean, event: DragEvent): void {
    const payload: IWidgetPayload = isWidget
      ? { kind: 'widget', label: 'A real widget' }
      : { kind: 'not-a-widget', label: 'Should be rejected' };
    event.dataTransfer?.setData('application/json', JSON.stringify(payload));
    // A second, marker-only MIME type carrying no value of its own —
    // `dataTransfer.types` (unlike `.getData()`) is readable during
    // dragenter/dragover, so this is what `outsideDropAccept` below
    // actually checks. Only the real widget sets it. This mirrors a
    // real bug fix confirmed earlier against a live browser: checking
    // the payload itself here (instead of `.types`) silently rejects
    // every drag, since `.getData()` only returns real values at drop
    // time, not during dragenter/dragover.
    if (isWidget) {
      event.dataTransfer?.setData('application/x-widget', '');
    }
  }

  outsideDropAccept = (dataTransfer: DataTransfer | null): boolean => {
    return !!dataTransfer?.types.includes('application/x-widget');
  };

  handleOutsideDrop({ x, y, w, h, dataTransfer }: { x: number; y: number; w: number; h: number; dataTransfer: DataTransfer | null }): void {
    const payload = readOutsideDropPayload<IWidgetPayload>(dataTransfer, 'application/json');
    this.lastPayload = JSON.stringify(payload);
    this.layout = [...this.layout, { h, i: String(this.nextId), w, x, y }];
    this.nextId += 1;
  }
}

// astro-docs/src/components/examples/34-outside-drop-accept-payload.vue
<template>
  <div class="demo-controls">
    <div
      class="outside-source outside-source--accepted"
      draggable="true"
      @dragstart="onDragStart(true, $event)">
      widget (accepted)
    </div>
    <div
      class="outside-source outside-source--rejected"
      draggable="true"
      @dragstart="onDragStart(false, $event)">
      not-a-widget (rejected)
    </div>
  </div>

  <div class="drop-zone-frame">
    <GridLayout
      v-model:layout="layout"
      allow-outside-drop
      :col-num="12"
      height-mode="fit"
      :outside-drop-accept="outsideDropAccept"
      :row-height="60"
      show-grid-lines
      @item-dropped-from-outside="onDropped">
      <GridItem
        v-for="item in layout"
        :key="item.i"
        :h="item.h"
        :i="item.i"
        :w="item.w"
        :x="item.x"
        :y="item.y">
        <div class="example-item">
          {{ item.i }}
        </div>
      </GridItem>
    </GridLayout>
  </div>

  <p class="demo-description">Last payload: {{ lastPayload ?? 'none yet' }}</p>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, readOutsideDropPayload, type TLayout } from 'keystone-dashboard-layout-vue';
  import 'keystone-dashboard-layout-vue/style.css';

  interface IWidgetPayload {
    kind: string;
    label: string;
  }

  const layout = ref<TLayout>([]);
  const lastPayload = ref<string | null>(null);
  let nextId = 0;

  function onDragStart(isWidget: boolean, event?: DragEvent): void {
    const payload: IWidgetPayload = isWidget
      ? { kind: 'widget', label: 'A real widget' }
      : { kind: 'not-a-widget', label: 'Should be rejected' };
    event?.dataTransfer?.setData('application/json', JSON.stringify(payload));
    // A second, marker-only MIME type carrying no value of its own —
    // `dataTransfer.types` (unlike `.getData()`) is readable during
    // dragenter/dragover, so this is what `outsideDropAccept` below
    // actually checks. Only the real widget sets it.
    if (isWidget) {
      event?.dataTransfer?.setData('application/x-widget', '');
    }
  }

  function outsideDropAccept(dataTransfer: DataTransfer | null): boolean {
    // Deliberately checks `.types`, not the payload itself — reading
    // `.getData()`'s actual value only works at `drop` time; during
    // dragenter/dragover (when this is called) it always returns an
    // empty string, so a payload-parsing check here would silently
    // reject every drag, real widget or not.
    return !!dataTransfer?.types.includes('application/x-widget');
  }

  function onDropped({ x, y, w, h, dataTransfer }: { x: number; y: number; w: number; h: number; dataTransfer: DataTransfer }): void {
    const payload = readOutsideDropPayload<IWidgetPayload>(dataTransfer, 'application/json');
    lastPayload.value = JSON.stringify(payload);
    layout.value.push({ h, i: String(nextId), w, x, y });
    nextId += 1;
  }
</script>

<style scoped>
.demo-controls {
  margin-bottom: 16px;
}

.drop-zone-frame {
  border: 1px dashed var(--kg-line-light);
  height: 200px;
}

.outside-source {
  border-radius: 6px;
  cursor: grab;
  display: inline-block;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.outside-source--accepted {
  background: var(--kg-amber);
  color: #2b1b02;
}

.outside-source--rejected {
  background: var(--kg-paper-3);
  border: 1px dashed var(--kg-line-light);
  color: var(--kg-text-lo-light);
  margin-left: 8px;
}

.demo-description {
  color: var(--kg-text-lo-light);
  font-size: 12.5px;
  font-family: var(--kg-font-mono);
  margin-top: 12px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
