// angular-examples-app/src/app/examples/42-pluggable-compaction.component.ts
import { Component, ViewChild } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import { ECompactType } from '@keystone-dashboard-layout/core';
import type { ICompactor, TLayout } from '@keystone-dashboard-layout/core';
import { LayoutJsonViewerComponent } from '../harness/layout-json-viewer.component';

type TMode = 'vertical' | 'horizontal' | 'none' | 'vertical-overlap' | 'custom';

// A custom ICompactor — stacks every non-static item into a single
// left-hand column, one after another, ignoring x/width entirely.
// Deliberately dramatic/simple for clarity, not a realistic default.
const singleColumnCompactor: ICompactor = {
  type: 'single-column',
  compact(inputLayout) {
    let nextY = 0;
    return inputLayout.map((item) => {
      if (item.isStatic) return item;
      const positioned = { ...item, x: 0, y: nextY };
      nextY += item.h;
      return positioned;
    });
  },
};

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 2, i: '1', w: 3, x: 3, y: 0 },
  { h: 2, i: '2', w: 3, x: 6, y: 0 },
  { h: 2, i: '3', w: 3, x: 9, y: 0 },
];

@Component({
  selector: 'app-pluggable-compaction-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, LayoutJsonViewerComponent],
  template: `
    <div class="demo-controls">
      <select class="demo-select" [value]="mode" (change)="onModeChange($event)">
        <option value="vertical">compactType: vertical</option>
        <option value="horizontal">compactType: horizontal</option>
        <option value="none">compactType: none</option>
        <option value="vertical-overlap">compactType: vertical-overlap</option>
        <option value="custom">custom compactor: single column</option>
      </select>
      <button class="demo-btn" type="button" (click)="scatter()">Scatter</button>
      <button class="demo-btn demo-btn--ghost" type="button" (click)="grid.compactNow()">Tidy up (compactNow)</button>
    </div>

    <kdl-grid-layout #grid [colNum]="12" [compactor]="compactor" [compactType]="compactType" [layout]="layout" (layoutChange)="layout = $event" [rowHeight]="60" [showGridLines]="true">
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="example-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>

    <layout-json-viewer [layout]="layout" />
  `,
  styles: [`
    .demo-select {
      background: var(--kg-paper);
      border: 1px solid var(--kg-line-light);
      border-radius: 6px;
      color: var(--kg-text-hi-light);
      font-size: 13px;
      padding: 4px 8px;
    }
    .demo-btn--ghost {
      background: transparent;
      border: 1px solid var(--kg-line-light);
      color: var(--kg-text-hi-light);
    }
  `],
})
export class PluggableCompactionDemoComponent {
  @ViewChild('grid') grid!: GridLayoutComponent;
  mode: TMode = 'vertical';
  layout: TLayout = initialLayout;
  compactType: ECompactType = ECompactType.VERTICAL;
  compactor: ICompactor | null = null;

  onModeChange(event: Event): void {
    this.mode = (event.target as HTMLSelectElement).value as TMode;
    switch (this.mode) {
      case 'horizontal':
        this.compactType = ECompactType.HORIZONTAL;
        break;
      case 'none':
        this.compactType = ECompactType.NONE;
        break;
      case 'vertical-overlap':
        this.compactType = ECompactType.VERTICAL_OVERLAP;
        break;
      default:
        this.compactType = ECompactType.VERTICAL;
    }
    this.compactor = this.mode === 'custom' ? singleColumnCompactor : null;
  }

  scatter(): void {
    this.layout = this.layout.map((item) => ({
      ...item,
      x: Math.floor(Math.random() * 9),
      y: Math.floor(Math.random() * 6),
    }));
  }
}

// astro-docs/src/components/examples/42-pluggable-compaction.vue
<template>
  <div class="demo-controls">
    <select
      v-model="mode"
      class="demo-select">
      <option value="vertical">compactType: vertical</option>
      <option value="horizontal">compactType: horizontal</option>
      <option value="none">compactType: none</option>
      <option value="vertical-overlap">compactType: vertical-overlap</option>
      <option value="custom">custom compactor: single column</option>
    </select>
    <button
      class="demo-btn"
      @click="scatter">Scatter</button>
    <button
      class="demo-btn demo-btn--ghost"
      @click="gridRef?.compactNow()">Tidy up (compactNow)</button>
  </div>

  <GridLayout
    ref="gridRef"
    v-model:layout="layout"
    :col-num="12"
    :compact-type="compactType"
    :compactor="customCompactor"
    :row-height="60"
    show-grid-lines>
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { computed, ref } from 'vue';
  import { GridLayout, GridItem, ECompactType, type TLayout, type ICompactor } from '@keystone-dashboard-layout/vue';
  import '@keystone-dashboard-layout/vue/style.css';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  type TMode = 'vertical' | 'horizontal' | 'none' | 'vertical-overlap' | 'custom';

  const mode = ref<TMode>('vertical');

  const compactType = computed(() => {
    switch (mode.value) {
      case 'horizontal': return ECompactType.HORIZONTAL;
      case 'none': return ECompactType.NONE;
      case 'vertical-overlap': return ECompactType.VERTICAL_OVERLAP;
      default: return ECompactType.VERTICAL;
    }
  });

  // A custom ICompactor — stacks every non-static item into a single
  // left-hand column, one after another, ignoring x/width entirely.
  // Deliberately dramatic/simple for clarity, not a realistic default.
  const singleColumnCompactor: ICompactor = {
    type: 'single-column',
    compact(inputLayout) {
      let nextY = 0;
      return inputLayout.map(item => {
        if (item.isStatic) return item;
        const positioned = { ...item, x: 0, y: nextY };
        nextY += item.h;
        return positioned;
      });
    },
  };

  const customCompactor = computed(() => (mode.value === 'custom' ? singleColumnCompactor : null));

  const gridRef = ref<InstanceType<typeof GridLayout>>();
  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 3, x: 0, y: 0 },
    { h: 2, i: '1', w: 3, x: 3, y: 0 },
    { h: 2, i: '2', w: 3, x: 6, y: 0 },
    { h: 2, i: '3', w: 3, x: 9, y: 0 },
  ]);

  function scatter(): void {
    layout.value = layout.value.map(item => ({
      ...item,
      x: Math.floor(Math.random() * 9),
      y: Math.floor(Math.random() * 6),
    }));
  }
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.demo-select {
  border: 1px solid var(--kg-line-light);
  border-radius: 6px;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 4px 8px;
}

.demo-btn {
  background: var(--kg-blueprint);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.demo-btn--ghost {
  background: transparent;
  border: 1px solid var(--kg-line-light);
  color: var(--kg-text-hi-light);
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
