// angular-examples-app/src/app/examples/43-undo-redo.component.ts
import { Component, ViewChild } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import type { TLayout } from '@keystone-dashboard-layout/core';
import { ExampleNumberFieldComponent } from '../harness/example-number-field.component';
import { LayoutJsonViewerComponent } from '../harness/layout-json-viewer.component';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 2, x: 0, y: 0 },
  { h: 2, i: '1', w: 2, x: 2, y: 0 },
  { h: 2, i: '2', w: 2, x: 4, y: 0 },
];

@Component({
  selector: 'app-undo-redo-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, ExampleNumberFieldComponent, LayoutJsonViewerComponent],
  template: `
    <div class="demo-controls">
      <button class="demo-btn" type="button" [disabled]="!grid.canUndo" (click)="undo()">Undo</button>
      <button class="demo-btn" type="button" [disabled]="!grid.canRedo" (click)="redo()">Redo</button>
      <button class="demo-btn demo-btn--ghost" type="button" (click)="addItem()">Add item</button>
      <example-number-field [value]="undoHistoryLimit" (valueChange)="undoHistoryLimit = $event" label="undoHistoryLimit" [min]="1" [max]="20"></example-number-field>
    </div>

    <kdl-grid-layout #grid [colNum]="12" [enableUndoRedo]="true" [layout]="layout" (layoutChange)="handleLayoutChange($event)" [rowHeight]="60" [showGridLines]="true" [undoHistoryLimit]="undoHistoryLimit">
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="example-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>

    <layout-json-viewer [layout]="layout" />
  `,
  styles: [`
    .demo-btn {
      background: var(--kg-blueprint);
      border: none;
      border-radius: 6px;
      color: white;
      cursor: pointer;
      font-family: var(--kg-font-mono);
      font-size: 12px;
      padding: 6px 12px;
    }
    .demo-btn:disabled {
      cursor: not-allowed;
      opacity: 0.4;
    }
    .demo-btn--ghost {
      background: transparent;
      border: 1px solid var(--kg-line-light);
      color: var(--kg-text-hi-light);
    }
  `],
})
export class UndoRedoDemoComponent {
  @ViewChild('grid') grid!: GridLayoutComponent;
  layout: TLayout = initialLayout;
  // Set well below the library's own default (50) specifically so the
  // cap itself is easy to observe: add more items than the limit, then
  // keep undoing — canUndo becomes false before every addition is
  // undone, since the oldest snapshot was already dropped to stay
  // under it.
  undoHistoryLimit = 3;
  private nextId = 3;
  // canUndo/canRedo are plain fields on the imperative handle, not
  // reactive — Angular's own change detection re-checks the template
  // (and so [disabled]) on every layoutChange/undo/redo call already,
  // so no extra tick-counter workaround is needed the way a snapshot
  // read in a purely event-driven context sometimes requires.

  handleLayoutChange(next: TLayout): void {
    this.layout = next;
  }

  undo(): void {
    this.grid.undo();
  }

  redo(): void {
    this.grid.redo();
  }

  addItem(): void {
    const id = String(this.nextId);
    this.nextId += 1;
    this.layout = [...this.layout, { h: 2, i: id, w: 2, x: 0, y: Infinity }];
  }
}

// astro-docs/src/components/examples/43-undo-redo.vue
<template>
  <div class="demo-controls">
    <button
      class="demo-btn"
      :disabled="!gridRef?.canUndo"
      @click="gridRef?.undo()">Undo</button>
    <button
      class="demo-btn"
      :disabled="!gridRef?.canRedo"
      @click="gridRef?.redo()">Redo</button>
    <button
      class="demo-btn demo-btn--ghost"
      @click="addItem">Add item</button>
    <ExampleNumberField
      v-model="undoHistoryLimit"
      label="undoHistoryLimit"
      :max="20"
      :min="1" />
  </div>

  <GridLayout
    ref="gridRef"
    v-model:layout="layout"
    :col-num="12"
    enable-undo-redo
    :row-height="60"
    show-grid-lines
    :undo-history-limit="undoHistoryLimit">
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">
        {{ item.i }}
      </div>
    </GridItem>
  </GridLayout>

  <LayoutJsonViewer :layout="layout" />
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from 'keystone-dashboard-layout-vue';
  import 'keystone-dashboard-layout-vue/style.css';
  import ExampleNumberField from '../harness/ExampleNumberField.vue';
  import LayoutJsonViewer from '../harness/LayoutJsonViewer.vue';

  const layout = ref<TLayout>([
    { h: 2, i: '0', w: 2, x: 0, y: 0 },
    { h: 2, i: '1', w: 2, x: 2, y: 0 },
    { h: 2, i: '2', w: 2, x: 4, y: 0 },
  ]);

  const gridRef = ref<InstanceType<typeof GridLayout>>();
  let nextId = 3;
  // Set well below the library's own default (50) specifically so the
  // cap itself is easy to observe: add more items than the limit, then
  // keep undoing — canUndo becomes false before every addition is
  // undone, since the oldest snapshot was already dropped to stay
  // under it.
  const undoHistoryLimit = ref(3);

  function addItem(): void {
    layout.value.push({ h: 2, i: String(nextId), w: 2, x: 0, y: Infinity });
    nextId += 1;
  }
</script>

<style scoped>
.demo-controls {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 16px;
}

.demo-btn {
  background: var(--kg-blueprint);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  font-family: var(--kg-font-mono);
  font-size: 12px;
  padding: 6px 12px;
}

.demo-btn:disabled {
  cursor: not-allowed;
  opacity: 0.4;
}

.demo-btn--ghost {
  background: transparent;
  border: 1px solid var(--kg-line-light);
  color: var(--kg-text-hi-light);
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  height: 100%;
  justify-content: center;
  width: 100%;
}
</style>
