// astro-docs/src/components/examples-react/53-resize-direction-toggles.tsx
﻿import { useMemo, useState } from 'react';
import { GridLayout, GridItem } from 'keystone-dashboard-layout-react';
import 'keystone-dashboard-layout-react/style.css';
import type { TLayout, TResizeHandle } from 'keystone-dashboard-layout-core';
import ExampleToggle from '../harness-react/ExampleToggle';
import './53-resize-direction-toggles.css';

const initialLayout: TLayout = [{ h: 3, i: '0', w: 4, x: 4, y: 0 }];

export default function ResizeDirectionToggles() {
  const [n, setN] = useState(true);
  const [s, setS] = useState(true);
  const [e, setE] = useState(true);
  const [w, setW] = useState(false);
  const [ne, setNe] = useState(true);
  const [nw, setNw] = useState(false);
  const [se, setSe] = useState(true);
  const [sw, setSw] = useState(false);
  const [layout, setLayout] = useState<TLayout>(initialLayout);

  const resizeHandles = useMemo<TResizeHandle[]>(() => {
    const handles: TResizeHandle[] = [];
    if (n) handles.push('n');
    if (s) handles.push('s');
    if (e) handles.push('e');
    if (w) handles.push('w');
    if (ne) handles.push('ne');
    if (nw) handles.push('nw');
    if (se) handles.push('se');
    if (sw) handles.push('sw');
    return handles;
  }, [n, s, e, w, ne, nw, se, sw]);

  const layoutWithHandles = useMemo<TLayout>(
    () => layout.map((item) => ({ ...item, resizeHandles })),
    [layout, resizeHandles],
  );

  return (
    <>
      <div className="demo-controls">
        <ExampleToggle checked={n} label="N" onChange={setN} />
        <ExampleToggle checked={s} label="S" onChange={setS} />
        <ExampleToggle checked={e} label="E" onChange={setE} />
        <ExampleToggle checked={w} label="W" onChange={setW} />
        <ExampleToggle checked={ne} label="NE" onChange={setNe} />
        <ExampleToggle checked={nw} label="NW" onChange={setNw} />
        <ExampleToggle checked={se} label="SE" onChange={setSe} />
        <ExampleToggle checked={sw} label="SW" onChange={setSw} />
      </div>

      <GridLayout colNum={12} layout={layoutWithHandles} onLayoutChange={setLayout} rowHeight={60} showGridLines showResizeHandles>
        {layoutWithHandles.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{resizeHandles.length ? resizeHandles.join(', ') : 'none'}</div>
          </GridItem>
        ))}
      </GridLayout>
    </>
  );
}

// astro-docs/src/components/examples/53-resize-direction-toggles.vue
<template>
  <div class="demo-controls">
    <ExampleToggle
      v-model="n"
      label="N" />
    <ExampleToggle
      v-model="s"
      label="S" />
    <ExampleToggle
      v-model="e"
      label="E" />
    <ExampleToggle
      v-model="w"
      label="W" />
    <ExampleToggle
      v-model="ne"
      label="NE" />
    <ExampleToggle
      v-model="nw"
      label="NW" />
    <ExampleToggle
      v-model="se"
      label="SE" />
    <ExampleToggle
      v-model="sw"
      label="SW" />
  </div>

  <GridLayout
    v-model:layout="layout"
    :col-num="12"
    :row-height="60"
    show-grid-lines
    show-resize-handles>
    <GridItem
      v-for="item in layout"
      :key="item.i"
      :h="item.h"
      :i="item.i"
      :resize-handles="resizeHandles"
      :w="item.w"
      :x="item.x"
      :y="item.y">
      <div class="example-item">{{ resizeHandles.length ? resizeHandles.join(', ') : 'none' }}</div>
    </GridItem>
  </GridLayout>
</template>

<script lang="ts" setup>
  import { computed, ref } from 'vue';
  import { GridLayout, GridItem, type TLayout } from '@keystone-dashboard-layout/vue';
  import type { TResizeHandle } from '@keystone-dashboard-layout/core';
  import '@keystone-dashboard-layout/vue/style.css';
  import ExampleToggle from '../harness/ExampleToggle.vue';

  const n = ref(true);
  const s = ref(true);
  const e = ref(true);
  const w = ref(false);
  const ne = ref(true);
  const nw = ref(false);
  const se = ref(true);
  const sw = ref(false);

  const resizeHandles = computed<TResizeHandle[]>(() => {
    const handles: TResizeHandle[] = [];
    if (n.value) handles.push('n');
    if (s.value) handles.push('s');
    if (e.value) handles.push('e');
    if (w.value) handles.push('w');
    if (ne.value) handles.push('ne');
    if (nw.value) handles.push('nw');
    if (se.value) handles.push('se');
    if (sw.value) handles.push('sw');
    return handles;
  });

  const layout = ref<TLayout>([
    { h: 3, i: '0', w: 4, x: 4, y: 0 },
  ]);
</script>

<style scoped>
.demo-controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 16px;
  margin-bottom: 16px;
}

.example-item {
  align-items: center;
  background: var(--kg-panel);
  border: 1px solid var(--kg-line-light);
  border-radius: 8px;
  color: var(--kg-text-hi-light);
  display: flex;
  font-family: var(--kg-font-mono);
  font-size: 11px;
  height: 100%;
  justify-content: center;
  padding: 8px;
  text-align: center;
  width: 100%;
}
</style>
