// astro-docs/src/components/harness-react/ExampleNumberField.tsx
import './example-controls.css';

/**
 * React port of the Vue harness's own ExampleNumberField.vue — a
 * labeled number input matching ExampleToggle's look. Controlled
 * component (value/onChange), the React equivalent of Vue's v-model.
 */
export interface IExampleNumberFieldProps {
  value: number;
  onChange: (value: number) => void;
  label: string;
  min?: number;
  max?: number;
  step?: number;
}

export default function ExampleNumberField({ value, onChange, label, min, max, step = 1 }: IExampleNumberFieldProps) {
  return (
    <label className="number-field">
      <span className="number-field__label">{label}</span>
      <input
        className="number-field__input"
        max={max}
        min={min}
        onChange={(event) => onChange(Number(event.target.value))}
        step={step}
        type="number"
        value={value}
      />
    </label>
  );
}

// angular-examples-app/src/app/harness/example-number-field.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

/** Same shape as astro-docs's own harness-angular/example-number-field — see ExampleToggleComponent's own doc comment for why this is duplicated rather than shared. */
@Component({
  selector: 'example-number-field',
  standalone: true,
  template: `
    <label class="number-field">
      <span class="number-field__label">{{ label }}</span>
      <input
        class="number-field__input"
        type="number"
        [value]="value"
        [attr.min]="min"
        [attr.max]="max"
        [attr.step]="step"
        (change)="onChange($event)"
      />
    </label>
  `,
})
export class ExampleNumberFieldComponent {
  @Input({ required: true }) value = 0;
  @Input({ required: true }) label = '';
  @Input() min: number | null = null;
  @Input() max: number | null = null;
  @Input() step = 1;
  @Output() valueChange = new EventEmitter<number>();

  onChange(event: Event): void {
    this.valueChange.emit(Number((event.target as HTMLInputElement).value));
  }
}
