// packages/react/src/components/Grid/GridItemCloseButton.tsx
import type { JSX } from 'react';

export interface IGridItemCloseButtonProps {
  /** The id of the `GridItem` this button removes when clicked. Required — unlike Vue's own `-1` sentinel workaround, React's own type system already expresses "must be provided" directly, with no need for a magic default value to stand in for "no item." */
  i: string | number;
  /** Called with `i` when clicked. */
  onRemoveGridItem: (id: string | number) => void;
}

/**
 * The default close button rendered inside a `GridItem` when its own
 * `showCloseButton` resolves `true` — the React port of Vue's own
 * `CustomCloseButton.vue` (confirmed via a direct source read). Also
 * exported standalone, same as Vue's own version, for a consumer who
 * wants to render the identical button elsewhere (e.g. in a custom
 * header) and wire it to the same removal logic manually. Not used
 * internally by `GridItem` itself, which renders its own, separate
 * built-in close button (`.kdl-grid-item-close-button`) — this is a
 * standalone, opt-in utility with a matching visual style, same
 * relationship Angular's own `GridItemCloseButtonComponent` has to its
 * package's built-in close button.
 */
export function GridItemCloseButton({ i, onRemoveGridItem }: IGridItemCloseButtonProps): JSX.Element {
  return (
    <button
      aria-label="Close"
      className="kdl-custom-close-button"
      onClick={() => onRemoveGridItem(i)}
      type="button"
    >
      <span aria-hidden="true" className="kdl-custom-close-button-icon" />
    </button>
  );
}

// packages/angular/src/lib/grid-item-close-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

/**
 * The default close button rendered inside `GridItemComponent` when
 * `showCloseButton` is true. Also exported standalone from the
 * package's own public entry point, for a consumer who wants to render
 * the same button elsewhere (e.g. inside a custom header) and wire it
 * to their own removal logic manually.
 *
 * A direct port of Vue's own `CustomCloseButton.vue` (confirmed via a
 * direct source read), with one deliberate, justified deviation: Vue's
 * own `i` prop defaults to a `-1` "no item" sentinel (needed because
 * Vue's `withDefaults` requires *some* default value for every prop).
 * Angular has first-class support for a required input with no default
 * at all — `i` is `@Input({ required: true })` here instead, which is
 * strictly safer (a consumer genuinely cannot render this component
 * without supplying a real id) rather than blindly copying a workaround
 * Angular doesn't need.
 */
@Component({
  selector: 'kdl-custom-close-button',
  standalone: true,
  template: `
    <button type="button" class="kdl-custom-close-button" aria-label="Close" (click)="onClick()">
      <span aria-hidden="true" class="kdl-custom-close-button-icon"></span>
    </button>
  `,
})
export class GridItemCloseButtonComponent {
  /** The id of the `GridItemComponent` (or any other layout item) this button removes when clicked. */
  @Input({ required: true }) i!: string | number;
  /** Emitted with `i` when clicked — matches Vue's own `EGridItemEvent.REMOVE_ITEM` (kebab-cased as `remove-grid-item` in Vue templates); named `removeGridItem` here, distinct from `GridItemComponent`'s own local `removeItem` output, since this component has no relationship to any specific parent item at all — it's a standalone utility a consumer wires up manually. */
  @Output() readonly removeGridItem = new EventEmitter<string | number>();

  onClick(): void {
    this.removeGridItem.emit(this.i);
  }
}
