// astro-docs/src/components/examples-react/23-outside-drag-drop-multiple-grids.tsx
import { useRef, useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import '../examples-react/shared-example-item.css';
import './04-multiple-grids.css';
import './11-outside-drag-drop.css';

export default function OutsideDragDropMultipleGrids() {
  const [layoutA, setLayoutA] = useState<TLayout>([]);
  const [layoutB, setLayoutB] = useState<TLayout>([]);
  const nextId = useRef(0);

  function handleDragStart(event: React.DragEvent<HTMLDivElement>): void {
    event.dataTransfer.setData('text/plain', 'from-outside');
  }

  function handleDroppedA({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    setLayoutA((current) => [...current, { h, i: `a${nextId.current}`, w, x, y }]);
    nextId.current += 1;
  }

  function handleDroppedB({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    setLayoutB((current) => [...current, { h, i: `b${nextId.current}`, w, x, y }]);
    nextId.current += 1;
  }

  return (
    <>
      <div className="demo-controls">
        <div className="outside-source" draggable="true" onDragStart={handleDragStart}>
          drag me in
        </div>
      </div>

      <div className="grids-row">
        <div className="grid-column">
          <p className="grid-label">Grid A</p>
          <GridLayout allowOutsideDrop colNum={6} layout={layoutA} onLayoutChange={setLayoutA} onOutsideDrop={handleDroppedA} rowHeight={60} showGridLines>
            {layoutA.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
        <div className="grid-column">
          <p className="grid-label">Grid B</p>
          <GridLayout allowOutsideDrop colNum={6} layout={layoutB} onLayoutChange={setLayoutB} onOutsideDrop={handleDroppedB} rowHeight={60} showGridLines>
            {layoutB.map((item) => (
              <GridItem i={item.i} key={item.i}>
                <div className="example-item">{item.i}</div>
              </GridItem>
            ))}
          </GridLayout>
        </div>
      </div>
    </>
  );
}

// angular-examples-app/src/app/examples/23-outside-drag-drop-multiple-grids.component.ts
import { Component } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import type { TLayout } from '@keystone-dashboard-layout/core';

@Component({
  selector: 'app-outside-drag-drop-multiple-grids-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent],
  template: `
    <div class="demo-controls">
      <div class="outside-source" draggable="true" (dragstart)="handleDragStart($event)">drag me in</div>
    </div>

    <div class="grids-row">
      <div class="grid-column">
        <p class="grid-label">Grid A</p>
        <kdl-grid-layout [allowOutsideDrop]="true" [colNum]="6" [layout]="layoutA" (layoutChange)="layoutA = $event" (itemDroppedFromOutside)="handleDroppedA($event)" [rowHeight]="60" [showGridLines]="true">
          @for (item of layoutA; track item.i) {
            <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
              <div class="example-item">{{ item.i }}</div>
            </kdl-grid-item>
          }
        </kdl-grid-layout>
      </div>
      <div class="grid-column">
        <p class="grid-label">Grid B</p>
        <kdl-grid-layout [allowOutsideDrop]="true" [colNum]="6" [layout]="layoutB" (layoutChange)="layoutB = $event" (itemDroppedFromOutside)="handleDroppedB($event)" [rowHeight]="60" [showGridLines]="true">
          @for (item of layoutB; track item.i) {
            <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
              <div class="example-item">{{ item.i }}</div>
            </kdl-grid-item>
          }
        </kdl-grid-layout>
      </div>
    </div>
  `,
})
export class OutsideDragDropMultipleGridsDemoComponent {
  layoutA: TLayout = [];
  layoutB: TLayout = [];
  private nextId = 0;

  handleDragStart(event: DragEvent): void {
    event.dataTransfer?.setData('text/plain', 'from-outside');
  }

  handleDroppedA({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    this.layoutA = [...this.layoutA, { h, i: `a${this.nextId}`, w, x, y }];
    this.nextId += 1;
  }

  handleDroppedB({ x, y, w, h }: { x: number; y: number; w: number; h: number }): void {
    this.layoutB = [...this.layoutB, { h, i: `b${this.nextId}`, w, x, y }];
    this.nextId += 1;
  }
}
