// astro-docs/src/components/examples-react/45-switching-layouts-remount.tsx
﻿import { useRef, useState } from 'react';
import { GridLayout, GridItem, type IGridLayoutHandle } from 'keystone-dashboard-layout-react';
import 'keystone-dashboard-layout-react/style.css';
import type { TLayout } from 'keystone-dashboard-layout-core';
import ExampleToggle from '../harness-react/ExampleToggle';
import LayoutJsonViewer from '../harness-react/LayoutJsonViewer';
import '../examples-react/shared-example-item.css';
import './45-switching-layouts-remount.css';

const layoutA: TLayout = [
  { h: 2, i: 'a0', w: 2, x: 0, y: 0 },
  { h: 2, i: 'a1', w: 2, x: 2, y: 0 },
  { h: 2, i: 'a2', w: 2, x: 4, y: 0 },
];

// Deliberately the same length (3 items) as layoutA — this package's
// own controlled-component sync commits an undo point whenever the
// layout's own length changes (see the render-phase sync's own doc
// comment in GridLayout.tsx), which would otherwise fire on every
// switch regardless of whether anything was actually dragged,
// confounding this example's own demonstration of canUndo staying
// stale specifically from Layout A's own drag.
const layoutB: TLayout = [
  { h: 3, i: 'b0', w: 4, x: 0, y: 0 },
  { h: 3, i: 'b1', w: 4, x: 4, y: 0 },
  { h: 2, i: 'b2', w: 8, x: 0, y: 3 },
];

export default function SwitchingLayoutsRemount() {
  const [forceRemount, setForceRemount] = useState(false);
  const [layout, setLayout] = useState<TLayout>(() => layoutA.map((item) => ({ ...item })));
  const [currentLayoutName, setCurrentLayoutName] = useState<'A' | 'B'>('A');
  const gridRef = useRef<IGridLayoutHandle>(null);
  // Only meaningful while forceRemount is on — changing this changes
  // the GridLayout's own `key`, which is what actually triggers React
  // to unmount and remount the component (a fresh instance, all
  // internal state reset) rather than just reactively updating props
  // on the existing one. Incrementing on every switch (not just
  // toggling true/false once) means switching back and forth between
  // A and B remounts every time, not just the first switch after
  // enabling it.
  const gridKeyRef = useRef(0);
  const [, forceUpdate] = useState(0);

  function switchTo(target: 'a' | 'b'): void {
    setLayout((target === 'a' ? layoutA : layoutB).map((item) => ({ ...item })));
    setCurrentLayoutName(target === 'a' ? 'A' : 'B');
    gridKeyRef.current += 1;
    forceUpdate((tick) => tick + 1);
  }

  return (
    <>
      <div className="demo-controls">
        <ExampleToggle checked={forceRemount} label="Force remount on switch" onChange={setForceRemount} />
        <button className="demo-btn" onClick={() => switchTo('a')} type="button">Switch to Layout A</button>
        <button className="demo-btn" onClick={() => switchTo('b')} type="button">Switch to Layout B</button>
      </div>

      <GridLayout
        colNum={12}
        enableUndoRedo
        key={forceRemount ? gridKeyRef.current : 'stable'}
        layout={layout}
        onLayoutChange={setLayout}
        ref={gridRef}
        rowHeight={70}
        showGridLines
      >
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>

      <p className="demo-description">Current layout: <strong>{currentLayoutName}</strong></p>
      <p className="demo-description">canUndo: <strong>{String(gridRef.current?.canUndo ?? false)}</strong></p>

      <LayoutJsonViewer layout={layout} />
    </>
  );
}

// angular-examples-app/src/app/examples/45-switching-layouts-remount.component.ts
import { Component, ViewChild } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import type { TLayout } from '@keystone-dashboard-layout/core';
import { ExampleToggleComponent } from '../harness/example-toggle.component';
import { LayoutJsonViewerComponent } from '../harness/layout-json-viewer.component';

const layoutA: TLayout = [
  { h: 2, i: 'a0', w: 2, x: 0, y: 0 },
  { h: 2, i: 'a1', w: 2, x: 2, y: 0 },
  { h: 2, i: 'a2', w: 2, x: 4, y: 0 },
];

// Deliberately the same length (3 items) as layoutA — GridLayoutComponent
// commits an undo point whenever the layout's own length changes (see
// its own ngOnChanges), which would otherwise fire on every switch
// regardless of whether anything was actually dragged, confounding
// this example's own demonstration of canUndo staying stale
// specifically from Layout A's own drag.
const layoutB: TLayout = [
  { h: 3, i: 'b0', w: 4, x: 0, y: 0 },
  { h: 3, i: 'b1', w: 4, x: 4, y: 0 },
  { h: 2, i: 'b2', w: 8, x: 0, y: 3 },
];

@Component({
  selector: 'app-switching-layouts-remount-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, ExampleToggleComponent, LayoutJsonViewerComponent],
  template: `
    <div class="demo-controls">
      <example-toggle [checked]="forceRemount" (checkedChange)="forceRemount = $event" label="Force remount on switch"></example-toggle>
      <button class="demo-btn" type="button" (click)="switchTo('a')">Switch to Layout A</button>
      <button class="demo-btn" type="button" (click)="switchTo('b')">Switch to Layout B</button>
    </div>

    @if (mounted) {
      <kdl-grid-layout #grid [colNum]="12" [enableUndoRedo]="true" [layout]="layout" (layoutChange)="layout = $event" [rowHeight]="70" [showGridLines]="true">
        @for (item of layout; track item.i) {
          <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
            <div class="example-item">{{ item.i }}</div>
          </kdl-grid-item>
        }
      </kdl-grid-layout>
    }

    <p class="demo-description">Current layout: <strong>{{ currentLayoutName }}</strong></p>
    <p class="demo-description">canUndo: <strong>{{ grid?.canUndo ?? false }}</strong></p>

    <layout-json-viewer [layout]="layout" />
  `,
  styles: [`
    .demo-description {
      color: var(--kg-text-lo-light);
      font-size: 13px;
    }
  `],
})
export class SwitchingLayoutsRemountDemoComponent {
  @ViewChild('grid') grid?: GridLayoutComponent;
  forceRemount = false;
  layout: TLayout = layoutA.map((item) => ({ ...item }));
  currentLayoutName: 'A' | 'B' = 'A';
  mounted = true;

  switchTo(target: 'a' | 'b'): void {
    this.layout = (target === 'a' ? layoutA : layoutB).map((item) => ({ ...item }));
    this.currentLayoutName = target === 'a' ? 'A' : 'B';
    if (this.forceRemount) {
      // Angular has no literal `key` prop for a single element the way
      // React does — toggling a structural `@if` off then back on is
      // this package's own equivalent, genuinely destroying and
      // recreating the component (running ngOnDestroy/ngOnInit again,
      // resetting canUndo/the undo stack along with it) rather than
      // just updating its inputs in place.
      this.mounted = false;
      setTimeout(() => {
        this.mounted = true;
      });
    }
  }
}
