// astro-docs/src/components/examples-react/47-spacing-indicators.tsx
import { useState } from 'react';
import { GridLayout, GridItem } from '@keystone-dashboard-layout/react';
import '@keystone-dashboard-layout/react/style.css';
import type { TLayout } from '@keystone-dashboard-layout/core';
import ExampleToggle from '../harness-react/ExampleToggle';
import '../examples-react/shared-example-item.css';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 3, i: '1', w: 3, x: 5, y: 2 },
  { h: 2, i: '2', w: 3, x: 8, y: 0 },
];

export default function SpacingIndicators() {
  const [showSpacingGuides, setShowSpacingGuides] = useState(true);
  const [layout, setLayout] = useState<TLayout>(initialLayout);

  return (
    <>
      <div className="demo-controls">
        <ExampleToggle checked={showSpacingGuides} label="showSpacingGuides" onChange={setShowSpacingGuides} />
      </div>

      <GridLayout colNum={12} layout={layout} onLayoutChange={setLayout} rowHeight={60} showGridLines showSpacingGuides={showSpacingGuides}>
        {layout.map((item) => (
          <GridItem i={item.i} key={item.i}>
            <div className="example-item">{item.i}</div>
          </GridItem>
        ))}
      </GridLayout>
    </>
  );
}

// angular-examples-app/src/app/examples/47-spacing-indicators.component.ts
import { Component } from '@angular/core';
import { GridLayoutComponent, GridItemComponent } from '@keystone-dashboard-layout/angular';
import type { TLayout } from '@keystone-dashboard-layout/core';
import { ExampleToggleComponent } from '../harness/example-toggle.component';

const initialLayout: TLayout = [
  { h: 2, i: '0', w: 3, x: 0, y: 0 },
  { h: 3, i: '1', w: 3, x: 5, y: 2 },
  { h: 2, i: '2', w: 3, x: 8, y: 0 },
];

@Component({
  selector: 'app-spacing-indicators-demo',
  standalone: true,
  imports: [GridLayoutComponent, GridItemComponent, ExampleToggleComponent],
  template: `
    <div class="demo-controls">
      <example-toggle [checked]="showSpacingGuides" (checkedChange)="showSpacingGuides = $event" label="showSpacingGuides"></example-toggle>
    </div>

    <kdl-grid-layout [colNum]="12" [layout]="layout" (layoutChange)="layout = $event" [rowHeight]="60" [showGridLines]="true" [showSpacingGuides]="showSpacingGuides">
      @for (item of layout; track item.i) {
        <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
          <div class="example-item">{{ item.i }}</div>
        </kdl-grid-item>
      }
    </kdl-grid-layout>
  `,
})
export class SpacingIndicatorsDemoComponent {
  showSpacingGuides = true;
  layout: TLayout = initialLayout;
}
