// packages/react/e2e-fixture/scenarios/CrossGrid.tsx
import { useState } from 'react';
import { GridItem, GridLayout } from '../../src/index';
import type { TLayout } from '@keystone-dashboard-layout/core';

/**
 * Real-browser coverage for `allowCrossGridDrag` — dragging an
 * existing item from one live `GridLayout` into another. The unit
 * suite already covers the underlying accept/reject logic directly
 * (`handleDragEnd` called with a fabricated `clientX`/`clientY`), but
 * never through an actual pointer-driven gesture crossing real DOM
 * boundaries between two independently-measured containers — exactly
 * the class of thing the Vue port's own history found real,
 * browser-only bugs in for this same feature (native `mousemove`
 * unreliability during the gesture; see
 * `packages/react/e2e/cross-grid.spec.ts`).
 */
export default function CrossGrid(): React.JSX.Element {
  const [layoutA, setLayoutA] = useState<TLayout>([
    { h: 2, i: `a0`, w: 3, x: 0, y: 0 },
    // A static item in the same column, with a real gap between it and
    // "a0" once "a0" leaves — needed for the bin-pack-not-push-and-
    // compact regression test (dropping "a0" back into grid A should
    // land it back in the gap above "locked", not pushed below it).
    // Static items never move during compaction (confirmed directly:
    // `compactLayout`'s own `if(!l.isStatic)` guard), so this gap
    // persists regardless of `compactType` once "a0" is dragged out.
    { h: 2, i: `locked`, isStatic: true, w: 3, x: 0, y: 2 },
  ]);
  const [layoutB, setLayoutB] = useState<TLayout>([]);

  return (
    <div style={{ display: `flex`, gap: `16px` }}>
      <div data-testid="cross-grid-a" style={{ border: `1px solid #ccc`, minHeight: `200px`, width: `50%` }}>
        <GridLayout allowCrossGridDrag colNum={6} layout={layoutA} layoutId="grid-a" onLayoutChange={setLayoutA} rowHeight={80}>
          {layoutA.map(item => (
            <GridItem i={item.i} key={item.i}>
              <div className="fixture-item-content">
                {`Item ${item.i}`}
              </div>
            </GridItem>
          ))}
        </GridLayout>
      </div>
      <div data-testid="cross-grid-b" style={{ border: `1px solid #ccc`, minHeight: `200px`, width: `50%` }}>
        <GridLayout allowCrossGridDrag className="cross-grid-empty-target" colNum={6} layout={layoutB} layoutId="grid-b" onLayoutChange={setLayoutB} rowHeight={80}>
          {layoutB.map(item => (
            <GridItem i={item.i} key={item.i}>
              <div className="fixture-item-content">
                {`Item ${item.i}`}
              </div>
            </GridItem>
          ))}
        </GridLayout>
      </div>
    </div>
  );
}

// packages/angular/e2e-fixture/scenarios/cross-grid.component.ts
import { Component } from '@angular/core';
import { GridItemComponent } from '../../src/lib/grid-item.component';
import { GridLayoutComponent } from '../../src/lib/grid-layout.component';
import type { TLayout } from 'keystone-dashboard-layout-core';

/**
 * Real-browser coverage for `allowCrossGridDrag` — dragging an
 * existing item from one live `kdl-grid-layout` into another. The
 * unit suite already covers the underlying accept/reject logic
 * directly, but never through an actual pointer-driven gesture
 * crossing real DOM boundaries between two independently-measured
 * containers. Mirrors the Vue/React packages' own identical
 * `cross-grid` fixture, including the same static "locked" item (a
 * real gap above it once "a0" leaves — needed for the bin-pack-not-
 * push-and-compact regression test) and grid B's own
 * `cross-grid-empty-target` class (its own real, confirmed necessity
 * explained in `style.css`).
 */
@Component({
  imports: [GridLayoutComponent, GridItemComponent],
  selector: `app-cross-grid`,
  standalone: true,
  template: `
    <div style="display: flex; gap: 16px">
      <div data-testid="cross-grid-a" style="border: 1px solid #ccc; min-height: 200px; width: 50%">
        <kdl-grid-layout style="display: block; width: 100%" [allowCrossGridDrag]="true" [colNum]="6" [layout]="layoutA" layoutId="grid-a" [rowHeight]="80" (layoutChange)="layoutA = $event">
          @for (item of layoutA; track item.i) {
            <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h" [isStatic]="!!item.isStatic">
              <div class="fixture-item-content">{{ 'Item ' + item.i }}</div>
            </kdl-grid-item>
          }
        </kdl-grid-layout>
      </div>
      <div data-testid="cross-grid-b" style="border: 1px solid #ccc; min-height: 200px; width: 50%">
        <kdl-grid-layout style="display: block; width: 100%" [allowCrossGridDrag]="true" class="cross-grid-empty-target" [colNum]="6" [layout]="layoutB" layoutId="grid-b" [rowHeight]="80" (layoutChange)="layoutB = $event">
          @for (item of layoutB; track item.i) {
            <kdl-grid-item [i]="item.i" [x]="item.x" [y]="item.y" [w]="item.w" [h]="item.h">
              <div class="fixture-item-content">{{ 'Item ' + item.i }}</div>
            </kdl-grid-item>
          }
        </kdl-grid-layout>
      </div>
    </div>
  `,
})
export class CrossGridComponent {
  layoutA: TLayout = [
    { h: 2, i: `a0`, w: 3, x: 0, y: 0 },
    // A static item in the same column, with a real gap between it
    // and "a0" once "a0" leaves — static items never move during
    // compaction (core's own compact functions all skip isStatic
    // items), so this gap persists regardless of compactType once
    // "a0" is dragged out.
    { h: 2, i: `locked`, isStatic: true, w: 3, x: 0, y: 2 },
  ];
  layoutB: TLayout = [];
}
